# Site settings
title: 維新基地
header-img: img/home-bg.jpg
email: ceo.roninke@gmail.com
copyright_name: Ronin Ke
description: ""
baseurl: ""
url: "http://roninke.github.io"
twitter_username:
github_username:  roninke
facebook_username:
email_username:  ceo.roninke@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

# Sidebar settings
sidebar-about-description: "Ronin Ke<br>iOS Developer<br>UI/UX Designer<br>Startup Dreamer"
sidebar-avatar: /img/avatar-rke.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`
